-- MySQL Script generated by MySQL Workbench
-- 10/25/16 11:30:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdreserva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdreserva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdreserva` DEFAULT CHARACTER SET utf8 ;
USE `bdreserva` ;

-- -----------------------------------------------------
-- Table `bdreserva`.`quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdreserva`.`quarto` (
  `idquarto` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(4) NOT NULL,
  `andar` VARCHAR(2) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `caracteristicas` VARCHAR(512) NULL,
  `preco_diario` DECIMAL(7,2) NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `tipo_quarto` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idquarto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreserva`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdreserva`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tipo_documento` VARCHAR(45) NOT NULL,
  `num_documento` VARCHAR(11) NOT NULL,
  `endereco` VARCHAR(100) NULL,
  `telefone` VARCHAR(11) NULL,
  `email` VARCHAR(25) NULL,
  PRIMARY KEY (`idpessoa`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreserva`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdreserva`.`cliente` (
  `idpessoa` INT NOT NULL,
  `codigo_cliente` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idpessoa`),
  UNIQUE INDEX `codigo_cliente_UNIQUE` (`codigo_cliente` ASC),
  CONSTRAINT `fk_pessoa_cliente`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `bdreserva`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreserva`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdreserva`.`funcionario` (
  `idpessoa` INT NOT NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  `acesso` VARCHAR(15) NOT NULL,
  `login` VARCHAR(15) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idpessoa`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  CONSTRAINT `fk_pessoa_funcionario`
    FOREIGN KEY (`idpessoa`)
    REFERENCES `bdreserva`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreserva`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdreserva`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `unidade_medida` VARCHAR(20) NOT NULL,
  `preco_venda` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreserva`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdreserva`.`reserva` (
  `idreserva` INT NOT NULL AUTO_INCREMENT,
  `idquarto` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `idfuncionario` INT NOT NULL,
  `tipo_reserva` VARCHAR(20) NOT NULL,
  `data_reserva` DATE NOT NULL,
  `data_entrada` DATE NOT NULL,
  `data_saida` DATE NOT NULL,
  `custo_total` DECIMAL(7,2) NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_reserva_quarto_idx` (`idquarto` ASC),
  INDEX `fk_reserva_cliente_idx` (`idcliente` ASC),
  INDEX `fk_reserva_funcionario_idx` (`idfuncionario` ASC),
  CONSTRAINT `fk_reserva_quarto`
    FOREIGN KEY (`idquarto`)
    REFERENCES `bdreserva`.`quarto` (`idquarto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `bdreserva`.`cliente` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_funcionario`
    FOREIGN KEY (`idfuncionario`)
    REFERENCES `bdreserva`.`funcionario` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreserva`.`consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdreserva`.`consumo` (
  `idconsumo` INT NOT NULL AUTO_INCREMENT,
  `idreserva` INT NOT NULL,
  `idproduto` INT NOT NULL,
  `quantidade` DECIMAL(7,2) NOT NULL,
  `preco_venda` DECIMAL(7,2) NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idconsumo`),
  INDEX `fk_consumo_produto_idx` (`idproduto` ASC),
  INDEX `fk_consumo_reserva_idx` (`idreserva` ASC),
  CONSTRAINT `fk_consumo_produto`
    FOREIGN KEY (`idproduto`)
    REFERENCES `bdreserva`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumo_reserva`
    FOREIGN KEY (`idreserva`)
    REFERENCES `bdreserva`.`reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdreserva`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdreserva`.`pagamento` (
  `idpagamento` INT NOT NULL AUTO_INCREMENT,
  `idreserva` INT NOT NULL,
  `tipo_comprovante` VARCHAR(20) NOT NULL,
  `num_comprovante` VARCHAR(20) NOT NULL,
  `igv` DECIMAL(4,2) NOT NULL,
  `total_pagamento` DECIMAL(7,2) NOT NULL,
  `data_emissao` DATE NOT NULL,
  `data_pagamento` DATE NOT NULL,
  PRIMARY KEY (`idpagamento`),
  INDEX `fk_pagamento_reserva_idx` (`idreserva` ASC),
  CONSTRAINT `fk_pagamento_reserva`
    FOREIGN KEY (`idreserva`)
    REFERENCES `bdreserva`.`reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
